name: family-recipes
services:
  db:
    image: postgres:16
    container_name: recipe-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: recipe_db
    ports:
      - "5432:5432"
    volumes:
      - recipe-data:/var/lib/postgresql/data

volumes:
  recipe-data: